server:
  port: 8081

app:
  rules:
    conditions-path: "rules/conditions.json"
    transformations-path: "rules/transformations.json"

  kafka:
    input-topic: input-topic
    output-topic: output-topic
    error-topic: error-topic

logging:
  level:
    com.zetta.rule.application: DEBUG
    org.springframework: WARN
    org.apache.kafka: WARN
    org.hibernate: WARN

  file:
    name: logs/rule-engine.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rule_engine_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rule-engine-group
    producer:
      properties:
        spring.json.add.type.headers: false