app:
  rules:
    conditions-path: "rules/conditions.json"
    transformations-path: "rules/transformations.json"

logging:
  level:
    com.zetta.ruleengine: DEBUG
    org.springframework: INFO
    org.hibernate: WARN

  file:
    name: logs/rule-engine.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rule_engine_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}