app:
  rules:
    conditions-path: "rules/conditions.json"
    transformations-path: "rules/transformations.json"

logging:
  level:
    com.zetta.ruleengine: DEBUG
    org.springframework: INFO
    org.hibernate: WARN

  # File output (optional)
  file:
    name: logs/rule-engine.log

  # Console pattern
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"