server:
  port: 8081

app:
  rules:
    conditions-path: "/app/rules/conditions.json"
    transformations-path: "/app/rules/transformations.json"
  kafka:
    input-topic: input-topic
    output-topic: output-topic
    error-topic: error-topic

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: rule-engine-group
    producer:
      properties:
        spring.json.add.type.headers: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/rule_engine_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    com.zetta.rule.application: DEBUG
    org.springframework: INFO
    org.apache.kafka: INFO
    org.hibernate: WARN
    com.zaxxer.hikari: DEBUG

  file:
    name: /app/logs/rule-engine.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"